/**
 * People Content Data
 * 
 * Single source of truth for all people/team member content.
 * In the future, this data can be fetched from CMS/backend API.
 */

import type { Person } from "@/types/content";

export const PEOPLE: Person[] = [
  {
    id: "person-1",
    name: "Nguyễn Văn A",
    title: "Founder & Cố vấn tài chính",
    avatarUrl: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "nguyen.van.a@prosfin.vn",
    phone: "+84 123 456 789",
    tooltipBio: "Hơn 8 năm kinh nghiệm trong lĩnh vực kiểm toán và tư vấn tài chính tại các firm Big4.",
    bioShort: "Founder với 8+ năm kinh nghiệm Big4",
    bioLong: "Hơn 8 năm kinh nghiệm trong lĩnh vực kiểm toán và tư vấn tài chính tại các firm Big4. Chuyên sâu về tư vấn dòng tiền, kiểm soát nội bộ và quản trị rủi ro cho doanh nghiệp SME. Đã hỗ trợ hơn 100 doanh nghiệp trong việc cải thiện quản trị tài chính.",
    focusAreas: ["Tư vấn dòng tiền", "Kiểm soát nội bộ", "Quản trị rủi ro"],
    bestFor: ["SME", "Startup", "M&A"],
    tags: ["CFO", "Ex-Big4", "ACCA", "CPA"],
    serviceSlugs: ["advisor", "consulting"],
    priority: 10,
  },
  {
    id: "person-2",
    name: "Trần Thị B",
    title: "Cố vấn tài chính & Thuế",
    avatarUrl: "https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "tran.thi.b@prosfin.vn",
    phone: "+84 123 456 790",
    tooltipBio: "Chuyên gia về kế toán và thuế doanh nghiệp.",
    bioShort: "Chuyên gia thuế với kinh nghiệm Big4",
    bioLong: "Chuyên gia về kế toán và thuế doanh nghiệp, đã hỗ trợ hàng trăm doanh nghiệp vừa và nhỏ trong việc tối ưu nghĩa vụ thuế và xây dựng hệ thống kế toán bài bản. Có kinh nghiệm làm việc với cơ quan thuế và giải quyết các vấn đề thuế phức tạp.",
    focusAreas: ["Kế toán doanh nghiệp", "Tối ưu thuế", "Tuân thủ thuế"],
    bestFor: ["SME", "Manufacturing", "Retail"],
    tags: ["Tax", "Ex-Big4", "ACCA"],
    serviceSlugs: ["advisor", "consulting", "audit"],
    priority: 9,
  },
  {
    id: "person-3",
    name: "Lê Văn C",
    title: "Senior Financial Advisor",
    avatarUrl: "https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "le.van.c@prosfin.vn",
    phone: "+84 123 456 791",
    tooltipBio: "Chuyên gia về quản lý dòng tiền và tối ưu vốn lưu động.",
    bioShort: "Chuyên gia dòng tiền và vốn lưu động",
    bioLong: "Chuyên gia về quản lý dòng tiền và tối ưu vốn lưu động. Có kinh nghiệm làm việc với các doanh nghiệp sản xuất và thương mại, giúp cải thiện hiệu quả tài chính đáng kể. Đã hỗ trợ nhiều doanh nghiệp tối ưu chu kỳ công nợ và cải thiện dòng tiền.",
    focusAreas: ["Quản lý dòng tiền", "Tối ưu vốn lưu động", "Chu kỳ công nợ"],
    bestFor: ["Manufacturing", "Trading", "SME"],
    tags: ["CFO", "Cash Flow", "Working Capital"],
    serviceSlugs: ["execution-coaching", "consulting"],
    priority: 8,
  },
  {
    id: "person-4",
    name: "Phạm Thị D",
    title: "Financial Consultant",
    avatarUrl: "https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "pham.thi.d@prosfin.vn",
    phone: "+84 123 456 792",
    tooltipBio: "Chuyên gia về kiểm soát nội bộ và quản trị rủi ro tài chính.",
    bioShort: "Chuyên gia kiểm soát nội bộ và rủi ro",
    bioLong: "Chuyên gia về kiểm soát nội bộ và quản trị rủi ro tài chính. Đã hỗ trợ nhiều doanh nghiệp xây dựng hệ thống kiểm soát hiệu quả và tuân thủ quy định. Có kinh nghiệm đánh giá và cải thiện quy trình tài chính cho các doanh nghiệp quy mô vừa và lớn.",
    focusAreas: ["Kiểm soát nội bộ", "Quản trị rủi ro", "Tuân thủ"],
    bestFor: ["SME", "Manufacturing", "Services"],
    tags: ["Internal Control", "Risk Management", "Audit"],
    serviceSlugs: ["audit", "consulting"],
    priority: 7,
  },
  {
    id: "person-5",
    name: "Hoàng Văn E",
    title: "M&A Advisor",
    avatarUrl: "https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "hoang.van.e@prosfin.vn",
    phone: "+84 123 456 793",
    tooltipBio: "Chuyên gia về giao dịch M&A và cấu trúc vốn.",
    bioShort: "Chuyên gia M&A và cấu trúc vốn",
    bioLong: "Chuyên gia về giao dịch M&A và cấu trúc vốn. Có kinh nghiệm tư vấn cho các giao dịch mua bán, sáp nhập doanh nghiệp với giá trị từ vài tỷ đến hàng trăm tỷ đồng. Đã tham gia nhiều dự án due diligence và định giá doanh nghiệp.",
    focusAreas: ["M&A", "Cấu trúc vốn", "Định giá doanh nghiệp"],
    bestFor: ["M&A", "Private Equity", "Corporate Finance"],
    tags: ["M&A", "Capital Structure", "Valuation"],
    serviceSlugs: ["advisor", "consulting"],
    priority: 6,
  },
  {
    id: "person-6",
    name: "Vũ Thị F",
    title: "Tax Specialist",
    avatarUrl: "https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "vu.thi.f@prosfin.vn",
    phone: "+84 123 456 794",
    tooltipBio: "Chuyên gia về thuế doanh nghiệp và tối ưu nghĩa vụ thuế.",
    bioShort: "Chuyên gia thuế doanh nghiệp",
    bioLong: "Chuyên gia về thuế doanh nghiệp và tối ưu nghĩa vụ thuế. Có kinh nghiệm làm việc với cơ quan thuế và hỗ trợ doanh nghiệp trong các vấn đề về thuế phức tạp. Đã tư vấn cho nhiều doanh nghiệp về kế hoạch thuế và tối ưu nghĩa vụ thuế hợp pháp.",
    focusAreas: ["Thuế doanh nghiệp", "Tối ưu thuế", "Kế hoạch thuế"],
    bestFor: ["SME", "Manufacturing", "Trading"],
    tags: ["Tax", "Compliance", "Planning"],
    serviceSlugs: ["consulting", "audit"],
    priority: 5,
  },
  {
    id: "person-7",
    name: "Đỗ Văn G",
    title: "Financial Planning Advisor",
    avatarUrl: "https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "do.van.g@prosfin.vn",
    phone: "+84 123 456 795",
    tooltipBio: "Chuyên gia về lập kế hoạch tài chính và dự báo.",
    bioShort: "Chuyên gia lập kế hoạch và dự báo tài chính",
    bioLong: "Chuyên gia về lập kế hoạch tài chính và dự báo. Giúp doanh nghiệp xây dựng các mô hình tài chính chính xác và hỗ trợ ra quyết định dựa trên dữ liệu. Có kinh nghiệm xây dựng budget, forecast và financial models cho các doanh nghiệp quy mô khác nhau.",
    focusAreas: ["Lập kế hoạch tài chính", "Dự báo", "Financial Modeling"],
    bestFor: ["SME", "Startup", "Growth Stage"],
    tags: ["Financial Planning", "Forecasting", "Modeling"],
    serviceSlugs: ["execution-coaching", "consulting"],
    priority: 4,
  },
  {
    id: "person-8",
    name: "Bùi Thị H",
    title: "Internal Audit Specialist",
    avatarUrl: "https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "bui.thi.h@prosfin.vn",
    phone: "+84 123 456 796",
    tooltipBio: "Chuyên gia về kiểm toán nội bộ và đánh giá rủi ro.",
    bioShort: "Chuyên gia kiểm toán nội bộ",
    bioLong: "Chuyên gia về kiểm toán nội bộ và đánh giá rủi ro. Có kinh nghiệm làm việc tại các công ty kiểm toán lớn và hỗ trợ doanh nghiệp xây dựng hệ thống kiểm soát nội bộ. Đã thực hiện nhiều cuộc kiểm toán nội bộ và đánh giá rủi ro cho các doanh nghiệp.",
    focusAreas: ["Kiểm toán nội bộ", "Đánh giá rủi ro", "Kiểm soát nội bộ"],
    bestFor: ["SME", "Manufacturing", "Services"],
    tags: ["Audit", "Internal Control", "Risk Assessment"],
    serviceSlugs: ["audit"],
    priority: 3,
  },
  {
    id: "person-9",
    name: "Ngô Văn I",
    title: "CFO Advisor",
    avatarUrl: "https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "ngo.van.i@prosfin.vn",
    phone: "+84 123 456 797",
    tooltipBio: "Cố vấn CFO với hơn 10 năm kinh nghiệm trong quản lý tài chính doanh nghiệp.",
    bioShort: "CFO Advisor với 10+ năm kinh nghiệm",
    bioLong: "Cố vấn CFO với hơn 10 năm kinh nghiệm trong quản lý tài chính doanh nghiệp. Chuyên về chiến lược tài chính, quản trị vốn và tối ưu hiệu quả hoạt động. Đã từng đảm nhiệm vai trò CFO tại các doanh nghiệp quy mô vừa và lớn, có kinh nghiệm sâu về corporate finance và strategic planning.",
    focusAreas: ["Chiến lược tài chính", "Quản trị vốn", "Strategic Planning"],
    bestFor: ["Growth Stage", "M&A", "Corporate Finance"],
    tags: ["CFO", "Strategy", "Capital Management"],
    serviceSlugs: ["advisor", "mentor"],
    priority: 2,
  },
  {
    id: "person-10",
    name: "Lý Thị K",
    title: "Training & Development Lead",
    avatarUrl: "https://images.pexels.com/photos/3184405/pexels-photo-3184405.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop",
    email: "ly.thi.k@prosfin.vn",
    phone: "+84 123 456 798",
    tooltipBio: "Chuyên gia về đào tạo và phát triển năng lực tài chính.",
    bioShort: "Chuyên gia đào tạo và phát triển",
    bioLong: "Chuyên gia về đào tạo và phát triển năng lực tài chính. Thiết kế và tổ chức các chương trình đào tạo, hội thảo về quản lý tài chính cho doanh nghiệp và đội ngũ kế toán. Có kinh nghiệm xây dựng curriculum và training materials cho các chương trình đào tạo tài chính từ cơ bản đến nâng cao.",
    focusAreas: ["Đào tạo tài chính", "Phát triển năng lực", "Training Design"],
    bestFor: ["SME", "Accounting Teams", "Management"],
    tags: ["Training", "Development", "Education"],
    serviceSlugs: ["seminar", "mentor"],
    priority: 1,
  },
];

