/**
 * Posts Content Data
 * 
 * Single source of truth for all blog/post content (Our Thinking).
 * In the future, this data can be fetched from CMS/backend API.
 */

import type { Post } from "@/types/content";

export const POSTS: Post[] = [
  {
    id: "post-1",
    title: "5 dấu hiệu doanh nghiệp cần cố vấn tài chính",
    excerpt: "Khi nào doanh nghiệp nên tìm kiếm sự hỗ trợ từ cố vấn tài chính? Bài viết này sẽ giúp bạn nhận biết các dấu hiệu cần thiết.",
    date: "2024-01-15",
    tags: ["Tư vấn", "Quản lý"],
    href: "/insights/5-dau-hieu-can-co-van-tai-chinh",
    coverImage: "https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["advisor", "consulting"],
    readingTime: 5,
    category: "Tư vấn",
  },
  {
    id: "post-2",
    title: "Quản lý dòng tiền hiệu quả cho SME",
    excerpt: "Hướng dẫn chi tiết về cách quản lý dòng tiền hiệu quả cho các doanh nghiệp vừa và nhỏ, từ dự báo đến kiểm soát.",
    date: "2024-01-10",
    tags: ["Dòng tiền", "SME"],
    href: "/insights/quan-ly-dong-tien-hieu-qua",
    coverImage: "https://images.pexels.com/photos/50987/money-card-business-credit-card-50987.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["execution-coaching"],
    readingTime: 7,
    category: "Tư vấn",
  },
  {
    id: "post-3",
    title: "4 giai đoạn triển khai giải pháp tài chính",
    excerpt: "Quy trình 4 giai đoạn từ đánh giá đến tối ưu, giúp doanh nghiệp triển khai các giải pháp tài chính một cách hiệu quả.",
    date: "2024-01-05",
    tags: ["Triển khai", "Quy trình"],
    href: "/insights/4-giai-doan-trien-khai",
    coverImage: "https://images.pexels.com/photos/669610/pexels-photo-669610.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["execution-coaching"],
    readingTime: 6,
    category: "Coaching",
  },
  {
    id: "post-4",
    title: "Xây dựng hệ thống báo cáo quản trị",
    excerpt: "Hướng dẫn xây dựng hệ thống báo cáo quản trị hiệu quả, giúp lãnh đạo có thông tin kịp thời để ra quyết định.",
    date: "2023-12-28",
    tags: ["Báo cáo", "Quản trị"],
    href: "/insights/xay-dung-bao-cao-quan-tri",
    coverImage: "https://images.pexels.com/photos/164527/pexels-photo-164527.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["advisor", "consulting"],
    readingTime: 8,
    category: "Tư vấn",
  },
  {
    id: "post-5",
    title: "Tối ưu cấu trúc vốn cho doanh nghiệp",
    excerpt: "Phân tích các phương án tối ưu cấu trúc vốn, giúp doanh nghiệp cân bằng giữa rủi ro và chi phí vốn.",
    date: "2023-12-20",
    tags: ["Vốn", "Chiến lược"],
    href: "/insights/toi-uu-cau-truc-von",
    coverImage: "https://images.pexels.com/photos/210600/pexels-photo-210600.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["advisor", "consulting"],
    readingTime: 10,
    category: "Tư vấn",
  },
  {
    id: "post-6",
    title: "Mentoring đội ngũ tài chính: Tại sao quan trọng?",
    excerpt: "Tầm quan trọng của việc mentoring và phát triển đội ngũ tài chính nội bộ trong doanh nghiệp hiện đại.",
    date: "2023-12-15",
    tags: ["Mentoring", "Phát triển"],
    href: "/insights/mentoring-doi-ngu-tai-chinh",
    coverImage: "https://images.pexels.com/photos/259200/pexels-photo-259200.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["mentor"],
    readingTime: 6,
    category: "Đào tạo",
  },
  {
    id: "post-7",
    title: "Tuyển dụng nhân sự tài chính: Những điều cần biết",
    excerpt: "Kinh nghiệm và lưu ý khi tuyển dụng nhân sự tài chính, từ vị trí kế toán đến CFO.",
    date: "2023-12-10",
    tags: ["Tuyển dụng", "HR"],
    href: "/insights/tuyen-dung-nhan-su-tai-chinh",
    coverImage: "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["headhunt"],
    readingTime: 7,
    category: "Tuyển dụng",
  },
  {
    id: "post-8",
    title: "Đánh giá tài chính doanh nghiệp: Quy trình và phương pháp",
    excerpt: "Hướng dẫn quy trình và phương pháp đánh giá tài chính doanh nghiệp một cách toàn diện và chính xác.",
    date: "2023-12-05",
    tags: ["Đánh giá", "Phân tích"],
    href: "/insights/danh-gia-tai-chinh-doanh-nghiep",
    coverImage: "https://images.pexels.com/photos/159888/pexels-photo-159888.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["test", "advisor"],
    readingTime: 9,
    category: "Đánh giá",
  },
  {
    id: "post-9",
    title: "Kiểm toán nội bộ: Vai trò và lợi ích",
    excerpt: "Tìm hiểu về vai trò và lợi ích của kiểm toán nội bộ trong việc đảm bảo tính chính xác và tuân thủ.",
    date: "2023-11-28",
    tags: ["Kiểm toán", "Nội bộ"],
    href: "/insights/kiem-toan-noi-bo",
    coverImage: "https://images.pexels.com/photos/590020/pexels-photo-590020.jpeg?auto=compress&cs=tinysrgb&w=800",
    serviceSlugs: ["audit"],
    readingTime: 6,
    category: "Kiểm toán",
  },
];

