/**
 * Talent Pool Mock Data
 * 
 * Mock data cho talent pool để test UI.
 * Sẽ thay bằng API/CMS sau.
 * 
 * Privacy-by-design: Không có PII (chỉ candidateCode, không tên thật).
 */

import type { TalentPoolCandidate } from "./recruitment.catalog";

export const MOCK_TALENT_POOL: TalentPoolCandidate[] = [
  {
    candidateCode: "PF-TAL-00023",
    roleTitle: "Kế toán tổng hợp",
    level: "mid",
    skillTags: ["VAT", "CIT", "Excel", "QuickBooks", "Báo cáo tài chính"],
    industryTags: ["F&B", "Retail"],
    location: "Hà Nội",
    availability: "available",
    experienceYearsRange: "3–5",
    languages: ["VN", "EN"],
    summary: "Kinh nghiệm xử lý kế toán tổng hợp cho doanh nghiệp F&B và Retail. Thành thạo VAT, CIT và báo cáo tài chính.",
    badges: ["KTT"],
    updatedAt: "2024-01-15T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00024",
    roleTitle: "FP&A",
    level: "senior",
    skillTags: ["Financial Planning", "Budgeting", "Forecasting", "Power BI"],
    industryTags: ["Manufacturing", "Trading"],
    location: "TP.HCM",
    availability: "available",
    experienceYearsRange: "5–8",
    languages: ["VN", "EN"],
    summary: "Chuyên về Financial Planning & Analysis với kinh nghiệm trong Manufacturing và Trading. Thành thạo Power BI và forecasting models.",
    badges: ["Đã đào tạo ProsFIN", "CFO track"],
    updatedAt: "2024-01-14T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00025",
    roleTitle: "Kế toán trưởng (KTT)",
    level: "lead",
    skillTags: ["Internal Controls", "Compliance", "Team Management", "ERP"],
    industryTags: ["Manufacturing", "F&B"],
    location: "Hà Nội",
    availability: "interviewing",
    experienceYearsRange: "8–12",
    languages: ["VN", "EN"],
    summary: "Kế toán trưởng với kinh nghiệm quản lý team và xây dựng hệ thống kiểm soát nội bộ. Thành thạo ERP và compliance.",
    badges: ["KTT", "Đã đào tạo ProsFIN"],
    updatedAt: "2024-01-13T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00026",
    roleTitle: "Kế toán viên",
    level: "junior",
    skillTags: ["VAT", "Excel", "Invoice Processing"],
    industryTags: ["Retail"],
    location: "TP.HCM",
    availability: "available",
    experienceYearsRange: "1–2",
    languages: ["VN"],
    summary: "Kế toán viên với kinh nghiệm xử lý hóa đơn và VAT cho doanh nghiệp Retail. Đang tìm cơ hội phát triển.",
    badges: [],
    updatedAt: "2024-01-12T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00027",
    roleTitle: "CFO",
    level: "lead",
    skillTags: ["Strategic Planning", "M&A", "Investor Relations", "Financial Modeling"],
    industryTags: ["Trading", "Manufacturing"],
    location: "Hà Nội",
    availability: "not-available",
    experienceYearsRange: "12+",
    languages: ["VN", "EN"],
    summary: "CFO với kinh nghiệm lãnh đạo tài chính cho doanh nghiệp quy mô lớn. Thành thạo M&A và investor relations.",
    badges: ["CFO track"],
    updatedAt: "2024-01-11T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00028",
    roleTitle: "Kế toán thuế",
    level: "mid",
    skillTags: ["VAT", "CIT", "PIT", "Tax Compliance", "Tax Planning"],
    industryTags: ["F&B", "Retail", "Trading"],
    location: "TP.HCM",
    availability: "available",
    experienceYearsRange: "4–6",
    languages: ["VN", "EN"],
    summary: "Chuyên về thuế với kinh nghiệm xử lý VAT, CIT, PIT cho nhiều ngành. Thành thạo tax compliance và planning.",
    badges: [],
    updatedAt: "2024-01-10T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00029",
    roleTitle: "Cost Accountant",
    level: "senior",
    skillTags: ["Costing", "Cost Control", "Product Costing", "Excel"],
    industryTags: ["Manufacturing"],
    location: "Hà Nội",
    availability: "available",
    experienceYearsRange: "6–9",
    languages: ["VN", "EN"],
    summary: "Cost Accountant chuyên về costing và cost control trong Manufacturing. Thành thạo product costing và variance analysis.",
    badges: ["Đã đào tạo ProsFIN"],
    updatedAt: "2024-01-09T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00030",
    roleTitle: "Internal Auditor",
    level: "mid",
    skillTags: ["Internal Controls", "Risk Assessment", "Compliance", "Audit"],
    industryTags: ["F&B", "Retail"],
    location: "TP.HCM",
    availability: "available",
    experienceYearsRange: "3–5",
    languages: ["VN", "EN"],
    summary: "Internal Auditor với kinh nghiệm đánh giá rủi ro và kiểm soát nội bộ. Thành thạo compliance và audit procedures.",
    badges: [],
    updatedAt: "2024-01-08T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00031",
    roleTitle: "Kế toán quản trị",
    level: "senior",
    skillTags: ["Management Accounting", "Budgeting", "Cost Analysis", "Power BI"],
    industryTags: ["Manufacturing", "Trading"],
    location: "Hà Nội",
    availability: "interviewing",
    experienceYearsRange: "5–8",
    languages: ["VN", "EN"],
    summary: "Kế toán quản trị với kinh nghiệm budgeting và cost analysis. Thành thạo Power BI và management reporting.",
    badges: ["Đã đào tạo ProsFIN"],
    updatedAt: "2024-01-07T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00032",
    roleTitle: "Kế toán viên",
    level: "junior",
    skillTags: ["VAT", "Excel", "Invoice Processing", "Bank Reconciliation"],
    industryTags: ["Retail"],
    location: "Remote",
    availability: "available",
    experienceYearsRange: "1–2",
    languages: ["VN"],
    summary: "Kế toán viên với kinh nghiệm xử lý hóa đơn và bank reconciliation. Sẵn sàng làm việc remote.",
    badges: [],
    updatedAt: "2024-01-06T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00033",
    roleTitle: "Financial Controller",
    level: "lead",
    skillTags: ["Financial Reporting", "Internal Controls", "Team Management", "ERP"],
    industryTags: ["Manufacturing", "F&B"],
    location: "TP.HCM",
    availability: "available",
    experienceYearsRange: "10–15",
    languages: ["VN", "EN"],
    summary: "Financial Controller với kinh nghiệm quản lý team và xây dựng hệ thống báo cáo tài chính. Thành thạo ERP và internal controls.",
    badges: ["KTT", "CFO track"],
    updatedAt: "2024-01-05T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00034",
    roleTitle: "Kế toán thuế",
    level: "mid",
    skillTags: ["VAT", "CIT", "Tax Compliance", "Tax Software"],
    industryTags: ["Trading", "Retail"],
    location: "Hà Nội",
    availability: "available",
    experienceYearsRange: "3–5",
    languages: ["VN"],
    summary: "Kế toán thuế với kinh nghiệm xử lý VAT và CIT cho doanh nghiệp Trading và Retail. Thành thạo tax software.",
    badges: [],
    updatedAt: "2024-01-04T00:00:00Z",
    status: "public-basic",
  },
  {
    candidateCode: "PF-TAL-00035",
    roleTitle: "FP&A",
    level: "mid",
    skillTags: ["Budgeting", "Forecasting", "Excel", "Financial Modeling"],
    industryTags: ["F&B", "Retail"],
    location: "TP.HCM",
    availability: "available",
    experienceYearsRange: "3–5",
    languages: ["VN", "EN"],
    summary: "FP&A với kinh nghiệm budgeting và forecasting. Thành thạo Excel và financial modeling.",
    badges: [],
    updatedAt: "2024-01-03T00:00:00Z",
    status: "public-basic",
  },
];

