/**
 * Lead Export Functions
 * 
 * Frontend-only export functions for tool results.
 */

import type { ToolResult } from "@/types/tools";
import type { Lead } from "@/types/leads";

/**
 * Export tool result as JSON
 */
export function exportReportJSON(result: ToolResult): void {
  const dataStr = JSON.stringify(result, null, 2);
  const dataBlob = new Blob([dataStr], { type: "application/json" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `tool-report-${Date.now()}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export tool result as CSV
 */
export function exportReportCSV(result: ToolResult): void {
  const rows: string[] = [];

  // Metrics
  rows.push("Metric,Label,Value,Unit");
  result.metrics.forEach((metric) => {
    rows.push(
      `${metric.name},"${metric.label}",${metric.value},"${metric.unit || ""}"`
    );
  });

  // Flags
  if (result.flags.length > 0) {
    rows.push("");
    rows.push("Flag,Type,Severity,Message");
    result.flags.forEach((flag) => {
      rows.push(`"${flag.message}",${flag.type},${flag.severity}`);
    });
  }

  // Recommendations
  if (result.recommendations.length > 0) {
    rows.push("");
    rows.push("Recommendation,Type,Title,Description,Href");
    result.recommendations.forEach((rec) => {
      rows.push(
        `${rec.type},"${rec.title}","${rec.description}",${rec.href}`
      );
    });
  }

  const csvContent = rows.join("\n");
  const dataBlob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(dataBlob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `tool-report-${Date.now()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Export tool result as PDF (simplified, client-side)
 * 
 * Note: Full PDF generation would require a library like jsPDF.
 * This is a simplified version that opens print dialog.
 */
export function exportReportPDF(result: ToolResult, lead?: Lead): void {
  // Create a printable HTML document
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Tool Report</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 20px; }
          h1 { color: #333; }
          .metric { margin: 10px 0; padding: 10px; border-left: 3px solid #007bff; }
          .flag { margin: 10px 0; padding: 10px; border-left: 3px solid #ffc107; }
          .recommendation { margin: 10px 0; padding: 10px; background: #f8f9fa; }
          @media print { .no-print { display: none; } }
        </style>
      </head>
      <body>
        <h1>Tool Report</h1>
        ${lead ? `<p><strong>Generated for:</strong> ${lead.contact.name} (${lead.contact.email})</p>` : ""}
        ${result.summary ? `<p><strong>Summary:</strong> ${result.summary}</p>` : ""}
        
        <h2>Metrics</h2>
        ${result.metrics.map((m) => `
          <div class="metric">
            <strong>${m.label}:</strong> ${m.value} ${m.unit || ""}
            ${m.description ? `<br><small>${m.description}</small>` : ""}
          </div>
        `).join("")}
        
        ${result.flags.length > 0 ? `
          <h2>Flags</h2>
          ${result.flags.map((f) => `
            <div class="flag">
              <strong>${f.type.toUpperCase()}:</strong> ${f.message}
            </div>
          `).join("")}
        ` : ""}
        
        ${result.recommendations.length > 0 ? `
          <h2>Recommendations</h2>
          ${result.recommendations.map((r) => `
            <div class="recommendation">
              <strong>${r.title}:</strong> ${r.description}
            </div>
          `).join("")}
        ` : ""}
        
        ${result.insights && result.insights.length > 0 ? `
          <h2>Insights</h2>
          <ul>
            ${result.insights.map((i) => `<li>${i}</li>`).join("")}
          </ul>
        ` : ""}
        
        <p class="no-print"><small>Generated by ProsFIN Tools</small></p>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  // Wait for content to load, then print
  setTimeout(() => {
    printWindow.print();
  }, 250);
}

