import type { ServicePageConfig } from "../types";

export const oneledgerConfig: ServicePageConfig = {
  slug: "oneledger",
  title: "ProsFIN OneLedger™",
  description:
    "Tổ chức lại hệ thống kế toán theo chuẩn dữ liệu: một nguồn dữ liệu duy nhất, nhiều báo cáo đúng mục tiêu (thuế/ngân hàng/quản trị/định giá).",
  category: "Kế toán / Finance Transformation",
  tags: [
    { key: "one-source-of-truth", label: "One source of truth" },
    { key: "data-standardization", label: "Chuẩn hoá dữ liệu" },
    { key: "internal-controls", label: "Kiểm soát nội bộ" },
    { key: "management-reporting", label: "Báo cáo quản trị" },
    { key: "cfo-ready", label: "CFO-ready" },
  ],
  layoutVariant: "ledger-cockpit-layout",
  seo: {
    metaTitle: "OneLedger™ — Chuẩn hoá hệ thống kế toán để ra quyết định bằng dữ liệu thật | ProsFIN",
    metaDescription:
      "OneLedger™ giúp doanh nghiệp chuẩn hoá dữ liệu kế toán, thiết kế workflow + KSNB + reporting pack, sẵn sàng vay vốn/gọi vốn/M&A.",
    ogTitle: "ProsFIN OneLedger™",
    ogDescription: "Một nguồn dữ liệu duy nhất. Nhiều báo cáo đúng mục tiêu. Vận hành được. Chuyển giao được.",
    canonical: "/services/oneledger",
  },

  hero: {
    h1: "OneLedger™ — Một nguồn dữ liệu duy nhất. Nhiều báo cáo đúng mục tiêu.",
    subhead:
      "Chuẩn hoá hệ thống kế toán để CEO/CFO điều hành bằng số liệu thật, giảm rủi ro thuế–pháp lý và sẵn sàng vay vốn/gọi vốn/M&A.",
    chips: [
      { key: "oss", label: "One source of truth" },
      { key: "audit-trail", label: "Minh bạch truy xuất" },
      { key: "mgmt-pack", label: "Reporting pack theo mô hình DN" },
      { key: "controls", label: "KSNB vận hành được" },
      { key: "transfer", label: "Chuyển giao — không phụ thuộc 1 người" },
    ],
    trustLine: "Không làm thay kế toán. Không ghi sổ hộ. Không chạy báo cáo “đối phó”.",
    proofSlots: [
      { label: "Chuẩn hoá hệ thống", value: "Case slot" },
      { label: "Ngành triển khai", value: "Industries slot" },
      { label: "Bộ báo cáo bàn giao", value: "Deliverables slot" },
    ],
    ctas: [
      { label: "Đăng ký khảo sát OneLedger™ (30’)", action: "openCtaModal", source: "hero_primary" },
      { label: "Xem phạm vi bàn giao", action: "scrollTo", targetId: "deliverables", source: "hero_secondary" },
      { label: "Tôi phù hợp không? (60 giây)", action: "scrollTo", targetId: "scan", source: "hero_tertiary" },
    ],
    headline: "OneLedger™ — Một nguồn dữ liệu duy nhất. Nhiều báo cáo đúng mục tiêu.",
    ctaLegacy: {
      primary: "Đăng ký khảo sát OneLedger™ (30’)",
      secondary: "Xem phạm vi bàn giao",
      tertiary: "Tôi phù hợp không? (60 giây)",
    },
  },

  scan: {
    title: "Ledger Health Scan (60 giây)",
    subtitle: "Chọn tình trạng đúng với doanh nghiệp của bạn để nhận gợi ý module ưu tiên.",
    scoreThresholds: { low: 20, medium: 45, high: 70, critical: 85 },
    questions: [
      {
        id: "q_multi_ledgers",
        label: "DN đang có >1 bộ số liệu (thuế / nội bộ / ngân hàng)?",
        weight: 14,
        risks: ["data_integrity", "high_stakes_event"],
        recommendedModuleIds: ["M1", "M2"],
      },
      {
        id: "q_ceo_not_trust",
        label: "CEO/CFO không tin số liệu nội bộ khi ra quyết định?",
        weight: 10,
        risks: ["no_management_reporting", "data_integrity"],
        recommendedModuleIds: ["M5", "M1"],
      },
      {
        id: "q_slow_closing",
        label: "Closing cuối tháng thường > 10 ngày?",
        weight: 8,
        risks: ["process_bottlenecks"],
        recommendedModuleIds: ["M3", "M4"],
      },
      {
        id: "q_numbers_wrong",
        label: "Số liệu “đúng nghiệp vụ” nhưng “sai kết quả” (lãi/lỗ không hợp lý)?",
        weight: 10,
        risks: ["data_integrity", "process_bottlenecks"],
        recommendedModuleIds: ["M1", "M3"],
      },
      {
        id: "q_no_audit_trail",
        label: "Thiếu audit trail — khó truy vết chứng từ khi cần?",
        weight: 8,
        risks: ["control_weakness", "data_integrity"],
        recommendedModuleIds: ["M4", "M2"],
      },
      {
        id: "q_workflow_ragged",
        label: "Quy trình chứng từ rời rạc, phụ thuộc “thói quen từng người”?",
        weight: 8,
        risks: ["process_bottlenecks", "control_weakness"],
        recommendedModuleIds: ["M3", "M4"],
      },
      {
        id: "q_controls_weak",
        label: "Kiểm soát nội bộ yếu — dễ sai sót/gian lận/chi phí ẩn?",
        weight: 10,
        risks: ["control_weakness"],
        recommendedModuleIds: ["M4"],
      },
      {
        id: "q_depend_on_one",
        label: "Phụ thuộc mạnh vào 1 người (KTT/CFO), rủi ro nhân sự?",
        weight: 8,
        risks: ["org_dependency"],
        recommendedModuleIds: ["M6", "M8"],
      },
      {
        id: "q_high_stakes",
        label: "Chuẩn bị vay vốn / gọi vốn / thẩm định / M&A trong 12 tháng tới?",
        weight: 12,
        risks: ["high_stakes_event"],
        boosts: ["bank_loan", "fundraising", "mna"],
        recommendedModuleIds: ["M1", "M2", "M4", "M5"],
      },
      {
        id: "q_need_reporting",
        label: "BLĐ muốn nâng cấp báo cáo quản trị & KPI cảnh báo sớm?",
        weight: 8,
        risks: ["no_management_reporting"],
        recommendedModuleIds: ["M5"],
      },
    ],
    riskToModules: {
      data_integrity: ["M1", "M2"],
      process_bottlenecks: ["M3"],
      control_weakness: ["M4"],
      no_management_reporting: ["M5"],
      org_dependency: ["M6", "M8"],
      tech_fragmentation: ["M7"],
      high_stakes_event: ["M1", "M2", "M4", "M5"],
    },
    eventToRiskBoosts: {
      bank_loan: { addScore: 8, addRisks: ["high_stakes_event"] },
      fundraising: { addScore: 10, addRisks: ["high_stakes_event"] },
      mna: { addScore: 12, addRisks: ["high_stakes_event", "data_integrity"] },
      compliance_pressure: { addScore: 6, addRisks: ["control_weakness"] },
      expansion: { addScore: 4, addRisks: ["process_bottlenecks"] },
      restructuring: { addScore: 6, addRisks: ["org_dependency"] },
      succession: { addScore: 6, addRisks: ["org_dependency"] },
    },
    riskMap: {
      data: ["M1", "M2"],
      process: ["M3"],
      controls: ["M4"],
      reporting: ["M5"],
      org: ["M6", "M8"],
      tech: ["M7"],
      mna: ["M1", "M2", "M4", "M5"],
    },
    recommendMap: {
      q1: ["M1"],
      q4: ["M1"],
      q5: ["M1"],
      q6: ["M3", "M4"],
      q7: ["M3", "M4"],
      q8: ["M6", "M8"],
      q9: ["M1", "M2", "M4", "M5"],
      q10: ["M5"],
    },
    thresholds: { medium: 30, high: 60, critical: 80 },
    callouts: {
      highScore: "Bạn nên ưu tiên “Chốt số dư + Làm sạch dữ liệu nền” trước khi mở rộng báo cáo.",
      mnaTrigger: "Thẩm định yêu cầu số liệu nhất quán + truy xuất được. OneLedger ưu tiên chuẩn hoá audit trail.",
    },
  },

  sections: [
    { id: "hero", type: "heroCockpit" },
    { id: "scan", type: "heroCockpit", title: "Ledger Health Scan" },
    { id: "icp", type: "icpGate", title: "This is for you if…" },
    { id: "symptoms", type: "symptomsSticky", title: "Triệu chứng → Nguyên nhân gốc" },
    { id: "modules", type: "modulesBento", title: "Finance OS Modules" },
    { id: "timeline", type: "acceptanceTimeline", title: "Acceptance Gates" },
    { id: "deliverables", type: "deliverablesTabs", title: "Deliverables Vault" },
    { id: "commitments", type: "commitments", title: "ProsFIN Commitments" },
    { id: "rules", type: "engagementRules", title: "Engagement Rules" },
    { id: "faq", type: "faq", title: "FAQ" },
    { id: "people", type: "people", title: "Our People" },
    { id: "thinking", type: "thinking", title: "Our Thinking" },
    { id: "big-cta", type: "bigCta", title: "Book Assessment" },
  ],

  modules: [
    {
      id: "M1",
      name: "Baseline Close & Data Clean",
      tag: "Data",
      promise: "Chốt nền dữ liệu đủ tin cậy để mọi cải tiến phía sau không “đổ sông đổ bể”.",
      outcomes: ["Có số dư nền nhất quán", "Giảm sai lệch lặp lại", "Tạo baseline cho audit trail"],
      deliverables: ["Baseline trial balance / số dư nền", "Issues log + root causes", "Data cleaning playbook"],
      clientInputs: ["BCTC gần nhất", "Sổ cái", "Công nợ", "Tồn kho", "Top hợp đồng/đơn hàng"],
      pitfalls: ["Cut-off sai", "Mapping tài khoản không nhất quán", "Thiếu owner dữ liệu"],
      detailBlocks: [
        { type: "callout", title: "Mục tiêu", body: "Một baseline đủ tin cậy để mọi báo cáo (thuế/ngân hàng/quản trị) cùng truy về một gốc." },
        { type: "bullets", title: "Bạn nhận được", items: ["Baseline số dư nền", "Danh sách sai lệch", "Playbook làm sạch dữ liệu"] },
        { type: "preview", title: "Preview (placeholder)", placeholders: ["Trial balance sample", "Issues log sample", "Cut-off checklist"] },
      ],
    },
    {
      id: "M2",
      name: "Internal Accounting Standards Pack",
      tag: "Data",
      promise: "Chuẩn hoá cách thu thập–xử lý–cung cấp dữ liệu để số liệu phản ánh đúng hoạt động.",
      outcomes: ["Một chuẩn ghi nhận nội bộ thống nhất", "Audit trail rõ", "Giảm tranh cãi nội bộ về số"],
      deliverables: ["Internal standards pack", "Rules mapping & classification", "Output specs theo mục tiêu"],
      clientInputs: ["Chính sách bán/mua", "Danh mục sản phẩm", "Quy trình hiện tại"],
    },
    {
      id: "M3",
      name: "Workflow & Document Flow (E2E)",
      tag: "Process",
      promise: "Thiết kế luồng chứng từ end-to-end để tốc độ + đúng + truy xuất.",
      outcomes: ["Rút ngắn closing", "Giảm thất lạc chứng từ", "Rõ trách nhiệm từng bước"],
      deliverables: ["Sơ đồ luồng chứng từ", "RACI", "Checklist đóng sổ"],
      clientInputs: ["Danh sách phòng ban", "Luồng duyệt hiện tại", "Điểm nghẽn"],
    },
    {
      id: "M4",
      name: "Internal Controls & Checklists (KSNB)",
      tag: "Controls",
      promise: "Tạo hệ kiểm soát để ngăn sai sót, lãng phí, gian lận trước khi nó thành “vết thương lớn”.",
      outcomes: ["Giảm rủi ro vận hành", "Tăng tuân thủ", "Tạo nền minh bạch & thẩm định"],
      deliverables: ["Key controls", "Checklists theo quy trình", "Cơ chế đối soát & truy vết"],
      clientInputs: ["Luồng phê duyệt", "Hạn mức", "Hợp đồng/đơn hàng mẫu"],
    },
    {
      id: "M5",
      name: "Reporting Pack & Early Warning KPIs",
      tag: "Reporting",
      promise: "Báo cáo quản trị theo mô hình DN + KPI cảnh báo để CEO/CFO thấy vấn đề sớm.",
      outcomes: ["Ra quyết định nhanh", "Chủ động dòng tiền", "Nhìn rủi ro trước khi “nổ”"],
      deliverables: ["Weekly/monthly reporting pack", "KPI cảnh báo sớm", "Dashboard spec"],
      clientInputs: ["Mục tiêu BLĐ", "Chu kỳ báo cáo", "Unit economics / cấu trúc chi nhánh"],
    },
    {
      id: "M6",
      name: "Finance/Accounting Org Design",
      tag: "Org",
      promise: "Thiết kế phòng kế toán vận hành theo hệ thống, không theo “người”.",
      outcomes: ["Giảm phụ thuộc KTT", "Scale theo khối lượng", "Rõ vai – rõ trách nhiệm"],
      deliverables: ["Org chart", "JD + KPI vai trò", "Kế hoạch công tác theo chu kỳ"],
      clientInputs: ["Danh sách nhân sự", "Mô tả công việc hiện tại", "Pain điểm quản trị"],
    },
    {
      id: "M7",
      name: "Tech Enablement Advisory",
      tag: "Tech",
      promise: "Tư vấn lựa chọn/chuẩn hoá hệ thống kế toán để dữ liệu không bị chia cắt.",
      outcomes: ["Giảm thao tác tay", "Tăng đồng nhất dữ liệu", "Dễ mở rộng & tích hợp"],
      deliverables: ["Khuyến nghị hệ thống", "Integration spec (nếu cần)", "Vendor coordination checklist"],
      clientInputs: ["Hệ thống đang dùng", "Yêu cầu báo cáo", "Đau điểm vận hành"],
    },
    {
      id: "M8",
      name: "Operate & Transfer",
      tag: "Transfer",
      promise: "Chuyển giao để DN tự vận hành được — bền vững sau dự án.",
      outcomes: ["Đội nội bộ vận hành độc lập", "Duy trì chuẩn dữ liệu", "Cải tiến liên tục"],
      deliverables: ["Training kit", "Training sessions", "Review cadence & playbook"],
      clientInputs: ["Owner nội bộ", "Lịch vận hành", "Nhóm vận hành quy trình"],
    },
  ],

  gates: [
    {
      id: "G0",
      title: "Discovery & Scope Lock",
      inputs: ["Mục tiêu 12 tháng", "Bộ dữ liệu tối thiểu", "Stakeholders"],
      actions: ["Phỏng vấn + rà soát", "Chốt phạm vi", "Đặt tiêu chí nghiệm thu"],
      prosfinActions: ["Phỏng vấn + rà soát", "Chốt phạm vi", "Đặt tiêu chí nghiệm thu"],
      deliverables: ["Scope map", "Project plan", "Data request list"],
      successDefinition: ["Thống nhất output + cách đo + ownership"],
      relatedModuleIds: ["M1", "M2", "M3"],
    },
    {
      id: "G1",
      title: "Close & Clean Foundation",
      inputs: ["BCTC", "Sổ cái", "Công nợ", "Tồn kho"],
      actions: ["Phân tích sai lệch", "Chốt baseline", "Làm sạch nền"],
      prosfinActions: ["Phân tích sai lệch", "Chốt baseline", "Làm sạch nền"],
      deliverables: ["Baseline số dư nền", "Issues log", "Cleaning playbook"],
      successDefinition: ["Baseline nhất quán, truy xuất được"],
      relatedModuleIds: ["M1"],
    },
    {
      id: "G2",
      title: "Standards Pack",
      inputs: ["Mô hình kinh doanh", "Chính sách bán/mua", "Danh mục sản phẩm"],
      actions: ["Thiết kế chuẩn ghi nhận", "Chuẩn dữ liệu", "Mapping"],
      prosfinActions: ["Thiết kế chuẩn ghi nhận", "Chuẩn dữ liệu", "Mapping"],
      deliverables: ["Internal standards pack"],
      successDefinition: ["Quy tắc thống nhất, áp dụng được"],
      relatedModuleIds: ["M2"],
    },
    {
      id: "G3",
      title: "Workflow & Controls",
      inputs: ["Luồng chứng từ", "Luồng duyệt", "Điểm nghẽn"],
      actions: ["Thiết kế E2E flow", "RACI", "Key controls"],
      prosfinActions: ["Thiết kế E2E flow", "RACI", "Key controls"],
      deliverables: ["Process maps", "Checklists", "Control points"],
      successDefinition: ["Closing nhanh hơn, sai sót giảm"],
      relatedModuleIds: ["M3", "M4"],
    },
    {
      id: "G4",
      title: "Reporting + Transfer",
      inputs: ["Mục tiêu CEO/CFO", "Chu kỳ báo cáo", "Cơ cấu chi nhánh"],
      actions: ["Thiết kế reporting pack", "KPI cảnh báo", "Đào tạo"],
      prosfinActions: ["Thiết kế reporting pack", "KPI cảnh báo", "Đào tạo"],
      deliverables: ["Reporting pack spec", "KPI set", "Training kit"],
      successDefinition: ["Đội nội bộ dùng được, ra quyết định được"],
      relatedModuleIds: ["M5", "M6", "M8"],
    },
  ],

  deliverablesTabs: [
    {
      id: "D1",
      label: "Data Foundation",
      items: [
        { label: "Baseline trial balance / số dư nền" },
        { label: "Issues log & root causes" },
        { label: "Data cleaning playbook" },
      ],
      whoUsesIt: ["cfo", "chief-accountant"],
      decisionsEnabled: ["Chốt baseline tin cậy", "Ưu tiên xử lý sai lệch theo tác động"],
    },
    {
      id: "D2",
      label: "Standards & Controls",
      items: [
        { label: "Internal standards pack" },
        { label: "Process maps + RACI" },
        { label: "Key controls + checklists" },
      ],
      whoUsesIt: ["owner", "cfo", "chief-accountant"],
      decisionsEnabled: ["Giảm rủi ro tuân thủ", "Chuẩn hoá vận hành & truy xuất"],
    },
    {
      id: "D3",
      label: "Reporting Pack",
      items: [
        { label: "Weekly/monthly reporting pack" },
        { label: "Early warning KPIs" },
        { label: "Dashboard spec (placeholder)" },
      ],
      whoUsesIt: ["owner", "cfo"],
      decisionsEnabled: ["Ra quyết định theo dữ liệu", "Cảnh báo sớm cash/margin/AR/AP"],
    },
    {
      id: "D4",
      label: "Org & Transfer",
      items: [
        { label: "Org chart phòng kế toán" },
        { label: "JD + KPI vai trò" },
        { label: "Training kit + review cadence" },
      ],
      whoUsesIt: ["owner", "chief-accountant", "finance-team"],
      decisionsEnabled: ["Giảm phụ thuộc 1 người", "Scale theo giai đoạn phát triển"],
    },
  ],

  faq: [
    { q: "OneLedger™ khác gì ClearData™?", a: "OneLedger™ là hệ chuẩn vận hành kế toán (data + workflow + KSNB + reporting + org + transfer). ClearData™ thiên về chuẩn hoá dữ liệu/đầu vào theo nhu cầu kế toán dịch vụ." },
    { q: "ProsFIN có làm thay phòng kế toán không?", a: "Không. ProsFIN thiết kế hệ thống, chuẩn hoá và chuyển giao để đội nội bộ vận hành được." },
    { q: "DN cần chuẩn bị gì trước khảo sát?", a: "BCTC gần nhất, trial balance/sổ cái, công nợ, tồn kho, mô tả quy trình chứng từ, mục tiêu 12 tháng." },
    { q: "Nếu đang dùng ERP/phần mềm kế toán rồi thì sao?", a: "OneLedger™ vẫn phù hợp: tập trung chuẩn dữ liệu, mapping, workflow, kiểm soát và reporting; phần mềm chỉ là công cụ." },
    { q: "Timeline thường bao lâu?", a: "Tuỳ phạm vi; triển khai theo acceptance gates và nghiệm thu từng giai đoạn." },
    { q: "Bảo mật dữ liệu?", a: "Thiết kế theo nguyên tắc tối thiểu quyền truy cập, nhật ký truy xuất và quy trình chia sẻ dữ liệu theo scope." },
    { q: "OneLedger™ giúp vay vốn/gọi vốn/M&A như thế nào?", a: "Tạo số liệu nhất quán, truy xuất được, reporting đúng mục tiêu và giảm rủi ro thẩm định." },
    { q: "Nếu nội bộ không đồng thuận thì sao?", a: "ProsFIN chỉ nhận triển khai khi có owner nội bộ và BLĐ cam kết thay đổi theo dữ liệu." },
    { q: "DN nhỏ có làm được không?", a: "Có thể, nhưng cần đánh giá độ phức tạp và mục tiêu để chọn phạm vi tối ưu." },
    { q: "Khi nào ProsFIN từ chối triển khai?", a: "Khi DN chỉ muốn “làm đẹp báo cáo” mà không thay đổi hệ thống hoặc không sẵn sàng minh bạch dữ liệu." },
  ],

  proof: {
    caseSlots: [
      { title: "Case slot: Chuẩn hoá dữ liệu", summary: "Placeholder for before/after", metric: "Metric placeholder" },
      { title: "Case slot: Rút ngắn closing", summary: "Placeholder for before/after", metric: "Metric placeholder" },
    ],
    quoteSlots: [
      { quote: "Placeholder quote about trust in numbers.", author: "CEO Name", role: "CEO" },
      { quote: "Placeholder quote about audit trail and control.", author: "CFO Name", role: "CFO" },
    ],
  },

  explorer: {
    personas: ["owner", "cfo", "chief-accountant"],
    outcomes: ["Chuẩn hoá dữ liệu", "Kiểm soát nội bộ", "Báo cáo quản trị", "Sẵn sàng vay vốn/gọi vốn/M&A"],
    bestFor: ["DN đang tăng trưởng", "DN chuẩn bị thẩm định", "DN muốn bỏ “nhiều sổ” và vận hành một chuẩn"],
  },

  // Phase 6: Module bundles
  bundles: [
    {
      id: "bundle-a",
      name: "Foundation Pack",
      moduleIds: ["M1", "M2"],
      bestFor: ["Nhiều sổ / số liệu không tin", "DN mới bắt đầu chuẩn hoá"],
      outcomes: ["Một baseline tin cậy", "Chuẩn dữ liệu nội bộ", "Giảm tranh cãi về số"],
      deliverables: ["Baseline trial balance", "Internal standards pack", "Data cleaning playbook"],
      timeframe: "4-6 tuần",
    },
    {
      id: "bundle-b",
      name: "Controls Pack",
      moduleIds: ["M3", "M4"],
      bestFor: ["Closing chậm / rủi ro vận hành", "Thiếu kiểm soát nội bộ"],
      outcomes: ["Rút ngắn closing", "Giảm rủi ro vận hành", "Tăng tuân thủ"],
      deliverables: ["Workflow maps", "Key controls", "Checklists"],
      timeframe: "6-8 tuần",
    },
    {
      id: "bundle-c",
      name: "CFO Pack",
      moduleIds: ["M1", "M5", "M6"],
      bestFor: ["Báo cáo quản trị & KPI cảnh báo", "Thiếu báo cáo để ra quyết định"],
      outcomes: ["Báo cáo quản trị CFO-ready", "KPI cảnh báo sớm", "Ra quyết định nhanh"],
      deliverables: ["Reporting pack", "Early warning KPIs", "Org design"],
      timeframe: "8-10 tuần",
    },
    {
      id: "bundle-d",
      name: "Transaction Readiness",
      moduleIds: ["M1", "M2", "M4", "M5", "M8"],
      bestFor: ["Loan/fundraising/M&A", "Chuẩn bị thẩm định"],
      outcomes: ["Số liệu nhất quán, truy xuất được", "Reporting đúng chuẩn thẩm định", "Sẵn sàng transaction"],
      deliverables: ["Baseline + Standards", "Controls + Audit trail", "Reporting pack", "Transfer kit"],
      timeframe: "10-12 tuần",
    },
  ],
};

